/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type TextObject = {
  _type: "textObject";
  text?: string;
};

export type EmployeeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "employee";
};

export type TeamSection = {
  _type: "teamSection";
  eyebrow?: string;
  title?: string;
  text?: string;
  teamMembers?: Array<
    {
      _key: string;
    } & EmployeeReference
  >;
  buttons?: Array<
    {
      _key: string;
    } & Button
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Section = {
  _type: "section";
  eyebrow?: string;
  title?: string;
  content?: Array<
    | ({
        _key: string;
      } & TextObject)
    | ({
        _key: string;
      } & Button)
    | ({
        _key: string;
      } & CardContainer)
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
};

export type Button = {
  _type: "button";
  label?: string;
  link?: string;
  variant?: "primary" | "secondary" | "simple";
  icon?: boolean;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  writers?: Array<
    {
      _key: string;
    } & EmployeeReference
  >;
  publishedAt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  buttons?: Array<
    {
      _key: string;
    } & Button
  >;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
};

export type Menu = {
  _id: string;
  _type: "menu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  menuLinks?: Array<{
    pageName?: string;
    path?: Slug;
    _type: "menuLinkItem";
    _key: string;
  }>;
  headerMenuItems?: string;
  menuItem?: {
    employeeList?: Array<
      {
        _key: string;
      } & EmployeeReference
    >;
  };
  footerMenuItems?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  courseSections?: Array<{
    sectionTitle?: string;
    sectionText?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "section";
    _key: string;
  }>;
  length?: string;
  conditionsCourse?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  employees?: EmployeeReference;
  slug?: Slug;
  category?: "entreprenad" | "upphandling";
};

export type Tjanster = {
  _id: string;
  _type: "tjanster";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  eyebrow?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  experts?: Array<
    {
      _key: string;
    } & EmployeeReference
  >;
  sections?: Array<
    | ({
        _key: string;
      } & Section)
    | ({
        _key: string;
      } & TeamSection)
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  seo?: {
    small?: string;
    medium?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    long?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
};

export type CardContainer = {
  _type: "cardContainer";
  descriptionText?: string;
  hideDescription?: boolean;
  hideAccordion?: boolean;
  hideImage?: boolean;
  hideCardSmall?: boolean;
  accordions?: Array<{
    title?: string;
    description?: string;
    btnHref?: string;
    icon?: boolean;
    _type: "accordionItem";
    _key: string;
  }>;
};

export type Role = {
  _id: string;
  _type: "role";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Pageimage = {
  _id: string;
  _type: "pageimage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  page?: "medarbetare" | "juridikkurser" | "home";
  pageColor?: "#8AA2BD" | "#2D5A27" | "#333333";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  homeTitle?: string;
  homeEyebrow?: string;
  introSection?: {
    introTitle?: string;
    introText?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
  tjansterSection?: {
    tjansterTitle?: string;
    tjansterEyebrow?: string;
    tjansterText?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    accordionItem?: {
      title?: string;
      description?: string;
      btnHref?: string;
      icon?: boolean;
    };
  };
  employeeSection?: {
    employeeTitle?: string;
    employeeEyebrow?: string;
    employeeText?: string;
  };
  servicesCard?: CardContainer;
};

export type CourseCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "courseCategory";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  courseName?: string;
  aimCourse?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  aboutCourse?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  courseSections?: Array<{
    sectionTitle?: string;
    sectionText?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "section";
    _key: string;
  }>;
  length?: string;
  conditionsCourse?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  lecturer?: EmployeeReference;
  slug?: Slug;
  category?: CourseCategoryReference;
};

export type RoleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "role";
};

export type Employee = {
  _id: string;
  _type: "employee";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  slug?: Slug;
  roles?: Array<
    {
      _key: string;
    } & RoleReference
  >;
  number?: number;
  email?: string;
  educationList?: Array<{
    school?: string;
    education?: string;
    yearStart?: string;
    yearEnd?: string;
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type CourseCategory = {
  _id: string;
  _type: "courseCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Company = {
  _id: string;
  _type: "company";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  adress?: Array<{
    street?: string;
    postAdress?: string;
    postNumber?: number;
    country?: string;
    _type: "adressDetails";
    _key: string;
  }>;
  orgNumber?: string;
  phone?: number;
  email?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | TextObject
  | EmployeeReference
  | TeamSection
  | SanityImageAssetReference
  | Section
  | Button
  | Article
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Seo
  | Menu
  | Tjanster
  | CardContainer
  | Role
  | Post
  | Pageimage
  | Home
  | CourseCategoryReference
  | Course
  | RoleReference
  | Employee
  | CourseCategory
  | Company
  | MediaTag
  | Color
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../nextjs-wa-advokatbyra/src/sanity/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "home"][0]{    homeTitle,    homeEyebrow,    introSection {      introTitle,      introText,    },    tjansterSection {      tjansterTitle,      tjansterEyebrow,      tjansterText,    },    employeeSection {      employeeTitle,      employeeEyebrow,      employeeText,    },    servicesCard {      descriptionText,      hideDescription,      hideAccordion,      hideImage,      hideCardSmall,      accordions[] {        title,        description,        btnHref,        icon      }    },  }
export type HOMEPAGE_QUERY_RESULT = {
  homeTitle: string | null;
  homeEyebrow: string | null;
  introSection: {
    introTitle: string | null;
    introText: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | null;
  tjansterSection: {
    tjansterTitle: string | null;
    tjansterEyebrow: string | null;
    tjansterText: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | null;
  employeeSection: {
    employeeTitle: string | null;
    employeeEyebrow: string | null;
    employeeText: string | null;
  } | null;
  servicesCard: {
    descriptionText: string | null;
    hideDescription: boolean | null;
    hideAccordion: boolean | null;
    hideImage: boolean | null;
    hideCardSmall: boolean | null;
    accordions: Array<{
      title: string | null;
      description: string | null;
      btnHref: string | null;
      icon: boolean | null;
    }> | null;
  } | null;
} | null;

// Source: ../nextjs-wa-advokatbyra/src/sanity/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc)[0...12]{    _id,     title,     "slug": slug.current,     publishedAt  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
}>;

// Source: ../nextjs-wa-advokatbyra/src/sanity/queries.ts
// Variable: DATA_QUERY
// Query: *[(_type == "post" || _type == "employee") && slug.current == $slug][0]{    _type,    _id,    title,    firstName,    lastName,    role,    image,    bio,    body,    publishedAt,    educationList[]{      school,      year    }  }
export type DATA_QUERY_RESULT =
  | {
      _type: "employee";
      _id: string;
      title: null;
      firstName: string | null;
      lastName: string | null;
      role: null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
      bio: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      body: null;
      publishedAt: null;
      educationList: Array<{
        school: string | null;
        year: null;
      }> | null;
    }
  | {
      _type: "post";
      _id: string;
      title: string | null;
      firstName: null;
      lastName: null;
      role: null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      bio: null;
      body: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      publishedAt: string | null;
      educationList: null;
    }
  | null;

// Source: ../nextjs-wa-advokatbyra/src/sanity/queries.ts
// Variable: ALL_COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)] | order(courseName asc){    _id,    courseName,    "slug": slug.current,    "categoryTitle": category->title,    "lecturer": lecturer->{      firstName,      lastName,      role,      image    }  }
export type ALL_COURSES_QUERY_RESULT = Array<{
  _id: string;
  courseName: string | null;
  slug: string | null;
  categoryTitle: string | null;
  lecturer: {
    firstName: string | null;
    lastName: string | null;
    role: null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: ../nextjs-wa-advokatbyra/src/sanity/queries.ts
// Variable: COURSE_CATEGORIES_QUERY
// Query: *[_type == "courseCategory"]{    _id,    title,    "slug": slug.current  } | order(title asc)
export type COURSE_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
}>;

// Source: ../nextjs-wa-advokatbyra/src/sanity/queries.ts
// Variable: COURSE_CATEGORY_QUERY
// Query: *[_type == "course" && defined(category)] | order(category asc) {    category  }[0...100]
export type COURSE_CATEGORY_QUERY_RESULT = Array<{
  category: CourseCategoryReference;
}>;

// Source: ../nextjs-wa-advokatbyra/src/sanity/queries.ts
// Variable: COURSE_QUERY
// Query: *[_type == "course" && defined(slug.current)] | order(courseName asc) {    _id,    courseName,    "slug": slug.current,    "lecturer": lecturer->{      firstName,      lastName,      role,      image    }  }
export type COURSE_QUERY_RESULT = Array<{
  _id: string;
  courseName: string | null;
  slug: string | null;
  lecturer: {
    firstName: string | null;
    lastName: string | null;
    role: null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: ../nextjs-wa-advokatbyra/src/sanity/queries.ts
// Variable: COURSE_BY_CATEGORY_QUERY
// Query: *[_type == "courseCategory" && slug.current == $category][0]{    title,    description,    "courses": *[_type == "course" && category._ref == ^._id] | order(courseName asc) {      _id,      courseName,      "slug": slug.current    }  }
export type COURSE_BY_CATEGORY_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  courses: Array<{
    _id: string;
    courseName: string | null;
    slug: string | null;
  }>;
} | null;

// Source: ../nextjs-wa-advokatbyra/src/sanity/queries.ts
// Variable: COURSE_DETAIL_PAGE_QUERY
// Query: *[_type == "course" && slug.current == $slug][0]{    courseName,    aimCourse,    aboutCourse,    content,    image,    length,    conditionsCourse,    "categoryTitle": category->title,     courseSections[]{      sectionTitle,      sectionText    },    "lecturer": lecturer->{      firstName,      lastName,      "role": roles[0]->title,      number,       image,      email,      slug    }  }
export type COURSE_DETAIL_PAGE_QUERY_RESULT = {
  courseName: string | null;
  aimCourse: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  aboutCourse: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  content: null;
  image: null;
  length: string | null;
  conditionsCourse: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  categoryTitle: string | null;
  courseSections: Array<{
    sectionTitle: string | null;
    sectionText: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }> | null;
  lecturer: {
    firstName: string | null;
    lastName: string | null;
    role: string | null;
    number: number | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    email: string | null;
    slug: Slug | null;
  } | null;
} | null;

// Source: ../nextjs-wa-advokatbyra/src/sanity/queries.ts
// Variable: EMPLOYEES_QUERY
// Query: *[_type == "employee" && defined(slug.current)] | order(lastName asc){    _id,    firstName,    lastName,    number,    email,    bio,    "slug": slug.current,    image,    "roles": roles[]->{ title, "slug": slug.current }  }
export type EMPLOYEES_QUERY_RESULT = Array<{
  _id: string;
  firstName: string | null;
  lastName: string | null;
  number: number | null;
  email: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  slug: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  roles: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
}>;

// Source: ../nextjs-wa-advokatbyra/src/sanity/queries.ts
// Variable: EMPLOYEE_ROLE_QUERY
// Query: {    "role": *[_type == "role" && slug.current == $role][0] { title },    "employees": *[      _type == "employee" &&      $role in roles[]->slug.current &&      defined(slug.current)    ] | order(lastName asc) {      _id,      firstName,      lastName,      "roles": roles[]->{ title, "slug": slug.current },      "slug": slug.current,      image    }  }
export type EMPLOYEE_ROLE_QUERY_RESULT = {
  role: {
    title: string | null;
  } | null;
  employees: Array<{
    _id: string;
    firstName: string | null;
    lastName: string | null;
    roles: Array<{
      title: string | null;
      slug: string | null;
    }> | null;
    slug: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  }>;
};

// Source: ../nextjs-wa-advokatbyra/src/sanity/queries.ts
// Variable: ROLES_QUERY
// Query: *[    _type == "role" &&    count(*[      _type == "employee" &&      references(^._id)    ]) > 0  ]  | order(title asc) {    title,    "slug": slug.current  }
export type ROLES_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
}>;

// Source: ../nextjs-wa-advokatbyra/src/sanity/queries.ts
// Variable: EMPLOYEE_PAGE_QUERY
// Query: *[_type == "employee" && slug.current == $slug][0]{    firstName,    lastName,    "slug": slug.current,    number,    email,    bio,    image{      asset,      alt    },    "roles": roles[]->{ title, "slug": slug.current },    educationList[]{      school,      education,      yearStart,      yearEnd    }  }
export type EMPLOYEE_PAGE_QUERY_RESULT = {
  firstName: string | null;
  lastName: string | null;
  slug: string | null;
  number: number | null;
  email: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
  } | null;
  roles: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  educationList: Array<{
    school: string | null;
    education: string | null;
    yearStart: string | null;
    yearEnd: string | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "home"][0]{\n    homeTitle,\n    homeEyebrow,\n    introSection {\n      introTitle,\n      introText,\n    },\n    tjansterSection {\n      tjansterTitle,\n      tjansterEyebrow,\n      tjansterText,\n    },\n    employeeSection {\n      employeeTitle,\n      employeeEyebrow,\n      employeeText,\n    },\n    servicesCard {\n      descriptionText,\n      hideDescription,\n      hideAccordion,\n      hideImage,\n      hideCardSmall,\n      accordions[] {\n        title,\n        description,\n        btnHref,\n        icon\n      }\n    },\n  }\n': HOMEPAGE_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)] | order(publishedAt desc)[0...12]{\n    _id, \n    title, \n    "slug": slug.current, \n    publishedAt\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[(_type == "post" || _type == "employee") && slug.current == $slug][0]{\n    _type,\n    _id,\n    title,\n    firstName,\n    lastName,\n    role,\n    image,\n    bio,\n    body,\n    publishedAt,\n    educationList[]{\n      school,\n      year\n    }\n  }\n': DATA_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)] | order(courseName asc){\n    _id,\n    courseName,\n    "slug": slug.current,\n    "categoryTitle": category->title,\n    "lecturer": lecturer->{\n      firstName,\n      lastName,\n      role,\n      image\n    }\n  }\n': ALL_COURSES_QUERY_RESULT;
    '\n  *[_type == "courseCategory"]{\n    _id,\n    title,\n    "slug": slug.current\n  } | order(title asc)\n': COURSE_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "course" && defined(category)] | order(category asc) {\n    category\n  }[0...100]\n': COURSE_CATEGORY_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)] | order(courseName asc) {\n    _id,\n    courseName,\n    "slug": slug.current,\n    "lecturer": lecturer->{\n      firstName,\n      lastName,\n      role,\n      image\n    }\n  }\n': COURSE_QUERY_RESULT;
    '\n  *[_type == "courseCategory" && slug.current == $category][0]{\n    title,\n    description,\n    "courses": *[_type == "course" && category._ref == ^._id] | order(courseName asc) {\n      _id,\n      courseName,\n      "slug": slug.current\n    }\n  }\n': COURSE_BY_CATEGORY_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0]{\n    courseName,\n    aimCourse,\n    aboutCourse,\n    content,\n    image,\n    length,\n    conditionsCourse,\n    "categoryTitle": category->title, \n    courseSections[]{\n      sectionTitle,\n      sectionText\n    },\n    "lecturer": lecturer->{\n      firstName,\n      lastName,\n      "role": roles[0]->title,\n      number, \n      image,\n      email,\n      slug\n    }\n  }\n': COURSE_DETAIL_PAGE_QUERY_RESULT;
    '\n  *[_type == "employee" && defined(slug.current)] | order(lastName asc){\n    _id,\n    firstName,\n    lastName,\n    number,\n    email,\n    bio,\n    "slug": slug.current,\n    image,\n    "roles": roles[]->{ title, "slug": slug.current }\n  }\n': EMPLOYEES_QUERY_RESULT;
    '\n  {\n    "role": *[_type == "role" && slug.current == $role][0] { title },\n    "employees": *[\n      _type == "employee" &&\n      $role in roles[]->slug.current &&\n      defined(slug.current)\n    ] | order(lastName asc) {\n      _id,\n      firstName,\n      lastName,\n      "roles": roles[]->{ title, "slug": slug.current },\n      "slug": slug.current,\n      image\n    }\n  }\n': EMPLOYEE_ROLE_QUERY_RESULT;
    '\n  *[\n    _type == "role" &&\n    count(*[\n      _type == "employee" &&\n      references(^._id)\n    ]) > 0\n  ]\n  | order(title asc) {\n    title,\n    "slug": slug.current\n  }\n': ROLES_QUERY_RESULT;
    '\n  *[_type == "employee" && slug.current == $slug][0]{\n    firstName,\n    lastName,\n    "slug": slug.current,\n    number,\n    email,\n    bio,\n    image{\n      asset,\n      alt\n    },\n    "roles": roles[]->{ title, "slug": slug.current },\n    educationList[]{\n      school,\n      education,\n      yearStart,\n      yearEnd\n    }\n  }\n': EMPLOYEE_PAGE_QUERY_RESULT;
  }
}
